# Generated by Django 3.2.4 on 2021-06-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('código_producto', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('cantidad_productos', models.IntegerField()),
                ('fecha', models.DateField()),
                ('productos_ok', models.BooleanField(default=True)),
                ('cantidad_productos_ok', models.IntegerField(default=0)),
                ('merma', models.IntegerField(default=0)),
                ('precio_compra', models.IntegerField()),
                ('total_compra', models.IntegerField()),
                ('inversion_ok', models.BooleanField(default=True)),
                ('perdida', models.IntegerField(default=0)),
                ('precio_unitario', models.IntegerField()),
                ('nombre_local', models.CharField(max_length=100)),
                ('dirección_local', models.CharField(max_length=100)),
            ],
        ),
    ]
